### ISSUE TITLE
Add website updating instructions

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/dsc-wiki#1]
Add instructions somewhere on how to update/revise the Wiki. These instructions could be added to the Wiki, or to the README. For example, you could change the "Installation" page to "Setup", and add a section to the bottom of the Setup page called "How to update this website." 

Mention that files in `docs/src` can be edited in Jupyter, and commands to update webpages include: 

```
./release update-website
./release convert-documentation
./release convert-homepage
./release convert-tutorials
```

Also, maybe explaining briefly how the webpages are generated (using SOS package). What template are you using?

**Comment by gaow** [comment]
Instructions are added to the repo README.md:

https://github.com/stephenslab/dsc-wiki
