### ISSUE TITLE
Sidebar does not work on some systems

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc-wiki#10]
I wonder if I can get some help to implement this for DSC site:

http://getbootstrap.com/

It's not too much fancier, but has a banner and a logo.  If i can get some help that'd be great! Otherwise I'll revisit it later. I just think it would be good for our grant application. Current site looks a bit too academic (in a good way otherwise but not sure in CZI's eyes).

**Comment by pcarbo** [comment]
@gaow You should ask Arjun. He put together [John Novembre's new website](http://jnpopgen.org).

**Comment by gaow** [comment]
@pcarbo he's approach is to use `jeklly` + customized CSS. It looks great but we do not want to go that track because `ipynb-website` type of setup has apparent advantages (maybe backed up by the fact that Arjun has become a user of it :) )

I've recently poked the CSS / JS settings a bit to make the site a bit nicer. There are some glitches I still cannot easily fix. But I think the last thing I want to add is a search box. That will actually help readers find relevant stuff. This is perhaps as far as I want to go.

All these improvements are going into `jnbinder` which will also impact `ipynb-website.`

**Comment by gaow** [comment]
Search box added.

**Comment by pcarbo** [comment]
@gaow A couple observations:

+ I noticed that there is an empty gray box on the top-left of many pages, e.g., 
https://stephenslab.github.io/dsc-wiki/tutorials/Explore_Output.html

+ There should be a way to automatically allow the icons to move vertically as the window gets smaller (this is the idea of having a "responsive" website, e.g., like Bootstrap).

Overall, I think the website looks great and I don't think that many improvements need to be made.

**Comment by gaow** [comment]
@pcarbo I am not sure what empty gray box you are referring to ... they seem fine on my end:


![2018-02-22-08-27-53_scrot](https://user-images.githubusercontent.com/917985/36543751-4ffd1ad8-17aa-11e8-84e2-a69deaaf30e7.png)

What exactly do you see? The TOC might take a sec to load, though. Not sure how to optomize the JS codes.

> to move vertically as the window gets smaller

I believe the template is already responsive. The problem is currently those icons are actually a table of 4 columns each is an icon. The respnosive template must failed to deal with tables. We just need to code it differently I assume, not using a table? There are some other glitches RE CSS / JS here and there I was not able to fix within reasonable amount of time so I left them be. We can revisit later.

**Comment by pcarbo** [comment]
See the top-left corner of this screenshot.

![screenshot](https://user-images.githubusercontent.com/1503904/36561968-0af55d48-17db-11e8-8863-7a8001992c5e.png)

**Comment by gaow** [comment]
Hmm seems the entire sidebar is missing on your browser. Here is mine:

![2018-02-22-14-22-25_scrot](https://user-images.githubusercontent.com/917985/36562198-e4b31534-17db-11e8-894f-e28eae3a0220.png)

Unfortunately I cannot reproduce it on neither `Google Chrome` nor `Safari`. What is the browser that you are using? Does it has some web developer's feature that allows us to debug? I guess we might have to meet in person to figure this out. Let me reopen this ticket.

**Comment by pcarbo** [comment]
@gaow Firefox on macOS. I just checked and it works fine in Chrome.

**Comment by gaow** [comment]
Ahh thanks for spotting it! Same problem with Firefox on Linux. I fixed it. Turns out Firefox does not like Google Analytics so I removed that plugin. It is a feature nice to have, but compared to devoting more time to get it work on Firefox I just deleted it :)
