### ISSUE TITLE
A couple of TODO to current installation page

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc-wiki#11]
1. Change "Installation" to "Quick Start" on the website header -- need a minor update to `jnbinder`
2. Change step 5 to "Data extraction" once we have the R implementation.

**Comment by gaow** [comment]
> Change step 5 to "Data extraction" once we have the R implementation.

We can do this now -- basically update page `tutorial/Explore_Output.ipynb` with extracting results from `one_sample_location` example using the `dscrutils::dsc_query` function. Also should we make a new page `manual/DSC_dscrutils` to introduce the package? -- because down the line this package may have more plot features, even will connect to `workflowr` (will open a separate issue for it).

**Comment by gaow** [comment]
Also I'm still going to change the installation page to include some `conda` instructions. I want to make 2 points:

1. For people who never has used `conda` before or want a fresh installation, use `miniconda` not `anaconda`
2. Do not let `conda` edit the bash file! Instead, do something different eg. make a `~/.bash_conda`.

These points are in fact based on feedback from Joyce -- we were discussion installing DSC and adapting [this single cell benchmark](https://github.com/markrobinsonuzh/conquer) for the CZI project . It seems the couple of lines in `conda` added to her system bothered her a lot. The alternative approach should make sense to more people I assume.

**Comment by pcarbo** [comment]
> For people who never has used conda before or want a fresh installation, use miniconda not anaconda.

@gaow I don't think we should be making particular recommendations unless dsc2 works better with Miniconda. We can briefly point out the pros/cons of Miniconda and Anaconda, but we shouldn't provide a recommendation---this is really outside the scope of DSC as far as I'm concerned. (Should we also recommend Linux or Mac?)

> Do not let conda edit the bash file! Instead, do something different eg. make a ~/.bash_conda.

@gaow Again, this is outside the scope of DSC.

**Comment by pcarbo** [comment]
> Also should we make a new page manual/DSC_dscrutils to introduce the package? -- because down the line this package may have more plot features, even will connect to workflowr (will open a separate issue for it).

@gaow For now, I say no.

However, we should add an (optional) step to the Quick Start instructions for installing the dscrutils R package. (There we can refer the user to the package documentation which can be accessed from within R.)

I also agree that we should illustrate `dscrutils::dscquery` in the `Explore_Output.ipynb` tutorial.

**Comment by gaow** [comment]
> For now, I say no.

Sure.

> I also agree that we should illustrate dscrutils::dscquery in the Explore_Output.ipynb tutorial.

Working on it

> However, we should add an (optional) step to the Quick Start instructions for installing the dscrutils R package.

Well ... actually when DSC runs, if it realizes there are R modules involved, it will then automatically install `dscrutils` from github. As long as we keep bumping required version number they should also automatically get updates. So in principle users do not have to worry. But what they will have to worry is when this automatic process fails ...

Anyways, I have updated [the installation page](https://stephenslab.github.io/dsc-wiki/quick_start.html#Troubleshooting) adding a trouble shooting section that provides advice for people who are new to conda so that they do not mess up their env. It would be nice if you would add instructions for `dscrutils` installation explaining that manual installation is only necessary when automatic installation fails, or when users install developmental version not official releases.

**Comment by pcarbo** [comment]
> It would be nice if you would add instructions for dscrutils installation explaining that manual installation is only necessary when automatic installation fails, or when users install developmental version not official releases.

@gaow I've added instructions for installing the development version of `dscrutils`.

**Comment by gaow** [comment]
Thanks @pcarbo
