### ISSUE TITLE
Next goal for wiki contents

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc-wiki#12]
Below are from @stephens999 originally posted on slack:

## Overall organization

So, I think we have:

- Quickstart = install DSC and run your first DSC
Tutorials:
- Introduction: explain the basics of DSC and introduce DSC syntax (this document)
- Querying Results of DSC: the tutorial on querying. (edited)
And Examples:
links to examples of repos with DSCs without additional commentary
Reference:
reference pages
I would hold off on fixing other tutorials yet… I may have a view on these

## What's next

I’d like to make a list of features we should include in the follow-up.
Here’s a start:
- ability to define similar modules in one time with  shorthand (eg normal,t:normal.R, t.R etc)
- ability to define multiple modules by varying input parameters. eg n=100, 1000
- ability to do this across muliple arguments https://github.com/stephenslab/dsc2/issues/92
- ability to deal with different data types in R and python (comment from Gao: in general, what types of data are dealt with on DSC interface and how do they translate to R and Python codes)

**Comment by gaow** [comment]
Also, [this list](https://stephenslab.github.io/dsc-wiki/manual/6abac0b32750f5b1e337ebfb5d18c5e968bc7f1b.html#Documentation) keep track of material I (Gao) would like to add.

I think we are back to the 20:80 game. Currently maybe we focus on writing up the 20% of documentation that satisfies 80% of our readers.

**Comment by stephens999** [comment]
agreed.
I think the alias feature should be included in this follow up

**Comment by gaow** [comment]
Update: meeting with @stephens999 and @pcarbo here is the todo list from this meeting

## Home page
- [ ] Change top bar to "Home/Tutorials/Installation/Examples/Manual"
- [ ] Move first paragraph of intro to home page
- [ ] Replace the icon-ed links with narratives to home page with links to highlight where we want readers to look
   - cf: http://docs.bpipe.org/
   - Add a list of "why DSC"
   - Make it clear that big picture overview comes before installation
- [ ] Move the acknowledgement paragraph to the end of the page
- [ ] Change footer: remove copyright, add names of developers
- [ ] Change `DSC2` to `DSC`

##  Tutorials

Add tutorials

- [ ] Introduction to Dynamic Statistical Comparisons
- [ ] Introduction to basic syntax (part I)
- [ ] Introduction to basic syntax (part II)

Change this page: https://stephenslab.github.io/dsc-wiki/tutorials.html

- [ ] Make it more clear what to read first. Possibly add some narratives.

**Comment by pcarbo** [comment]
@gaow I suggest running `grep -r -i dsc2 *` inside the `dsc` and `dsc-wiki` repos to find other mentions of "DSC2".
