### ISSUE TITLE
Make side bar and wiki titles consistent

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc-wiki#13]
As discussed on slack, inconsistency between wiki side bar and titles raise issues. Currently side bar is just formatted HTML file names. 

But on the other hand, for example:

![2018-03-01-16-35-47_scrot](https://user-images.githubusercontent.com/917985/36873697-e457efd6-1d6e-11e8-8bc4-e72b460ccd02.png)

The displayed name can be very long on the side bar. I'm not sure how to best compromise this. I suppose I can use some way like:

```
> s = make_it_short('Quick start tutorial using inline executables')
> s
"Quick start ... executables"
```

Is that better than relying on HTML names?

**Comment by pcarbo** [comment]
@gaow It is okay to have shorter titles in TOC as long as it is clear which tutorials they refer to.

**Comment by gaow** [comment]
Current behavior:

![2018-03-02-10-01-26_scrot](https://user-images.githubusercontent.com/917985/36908399-b8d52454-1e00-11e8-9557-a3ab96d82cd9.png)

Looks better?

**Comment by pcarbo** [comment]
@gaow Sure, or you could wrap like the items in the TOC, which is what is done in one of the standard templates for rendering R Markdown documents, e.g.:
https://stephenslab.github.io/wflow-divvy/seasonal-trends.html

**Comment by gaow** [comment]
Sure, though maybe down the line as I'm a slow javascript programmer. Took me a while to even get this far :) Will keep it in mind though.
