### ISSUE TITLE
Replace the "Design" page

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc-wiki#14]
@stephens999 I initially had this page:

https://stephenslab.github.io/dsc-wiki/manual/Design_and_Features.html

that does (or at least is intended to) not use any DSC terminology to present a case of how a typical simulation works. It overlaps with the new intro you have put together. But my initial goal was to have two 5min pages to DSC: the page above is a 5min read without running anything, the page below is a 5 min page to just run DSC blindly:

https://stephenslab.github.io/dsc-wiki/tutorials/5_Minutes.html

I assume I can keep the 2nd link. What should we do with the first? Asking because this is not clear from #12

**Comment by pcarbo** [comment]
@gaow [This link](https://stephenslab.github.io/dsc-wiki/tutorials/Quick_Start.html) no longer works. Did you move the file?

**Comment by gaow** [comment]
@pcarbo it is now https://stephenslab.github.io/dsc-wiki/tutorials/5_Minutes.html

**Comment by pcarbo** [comment]
@gaow My feeling is that the `Design_and_Features.html` page should eventually be combined with `DSC_Introduction.html`.
