### ISSUE TITLE
Add CC license

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/dsc-wiki#2]
I suggest adding the [CC-BY license](https://creativecommons.org/licenses/by/4.0/legalcode), or a variant of this license, for content of this Wiki. Not required, but good practice (see for example the [Software Carpentry](https://swcarpentry.github.io/python-novice-inflammation/license) website).

**Comment by gaow** [comment]
Should we have an additional tab for this license, as with the Software Carpentry example, or we add it into the footnote?

**Comment by pcarbo** [comment]
Either approach seems fine to me because it would make the license visible from all the main pages.

**Comment by gaow** [comment]
Done 51b33b5f3f257739125341d0f471338f2aded1f7
