### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by dcgerard** [stephenslab/dsc-wiki#9]
In index.html, the links to doc/documentation/Command_Options.html, doc/tutorials/Quick_Start.html, and doc/documentation/DSC_Configuration.html don't work.

**Comment by gaow** [comment]
Thanks @dcgerard -- I've been changing the sites with a new template along with changes soon to be committed for DSC. The dust should settle within a week and I'll run a broken link checker then :)

**Comment by gaow** [comment]
Broken links listed here:

https://github.com/stephenslab/dsc-wiki/blob/master/development/check_link.txt

Not many of them but may not have time to fix tonight ...
